# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterIndexTogether(
            name='food',
            index_together=set([('id', 'slug')]),
        ),
    ]
