# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180803_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
